give @s cc:adamantite_block 64
give @s cc:aluminum_block 64
give @s cc:amethyst_block 64
give @s cc:black_steel_block 64
give @s cc:bronze_block 64
give @s cc:cobalt_block 64
give @s cc:electrum_block 64
give @s cc:lead_block 64
give @s cc:mythril_block 64
give @s cc:nickel_block 64
give @s cc:platinum_block 64
give @s cc:silver_block 64
give @s cc:steel_block 64
give @s cc:tin_block 64
give @s cc:titanium_block 64
give @s cc:tungsten_block 64
give @s cc:uranium_block 64
give @s cc:zinc_block 64
give @s cc:copper_block 64
give @s cc:brass_block 64