give @p cc:adamantite_block 64
give @p cc:aluminum_block 64
give @p cc:amethyst_block 64
give @p cc:black_steel_block 64
give @p cc:bronze_block 64
give @p cc:cobalt_block 64
give @p cc:electrum_block 64
give @p cc:lead_block 64
give @p cc:mythril_block 64
give @p cc:nickel_block 64
give @p cc:platinum_block 64
give @p cc:silver_block 64
give @p cc:steel_block 64
give @p cc:tin_block 64
give @p cc:titanium_block 64
give @p cc:tungsten_block 64
give @p cc:uranium_block 64
give @p cc:zinc_block 64
give @p cc::copper_block 64
give @p cc:brass_block 64