#bridge-file-version: #2
give @p cc:adamantite_ingot 64
give @p cc:aluminum_ingot 64
give @p cc:amethyst_ingot 64
give @p cc:black_steel_ingot 64
give @p cc:bronze_ingot 64
give @p cc:cobalt_ingot 64
give @p cc:electrum_ingot 64
give @p cc:lead_ingot 64
give @p cc:mythril_ingot 64
give @p cc:nickel_ingot 64
give @p cc:platinum_ingot 64
give @p cc:silver_ingot 64
give @p cc:steel_ingot 64
give @p cc:tin_ingot 64
give @p cc:titanium_ingot 64
give @p cc:tungsten_ingot 64
give @p cc:uranium_ingot 64
give @p cc:zinc_ingot 64
give @p cc::copper_ingot 64
give @p cc:brass_ingot 64