#bridge-file-version: #2
give @s cc:adamantite_ingot 64
give @s cc:aluminum_ingot 64
give @s cc:amethyst_ingot 64
give @s cc:black_steel_ingot 64
give @s cc:bronze_ingot 64
give @s cc:cobalt_ingot 64
give @s cc:electrum_ingot 64
give @s cc:lead_ingot 64
give @s cc:mythril_ingot 64
give @s cc:nickel_ingot 64
give @s cc:platinum_ingot 64
give @s cc:silver_ingot 64
give @s cc:steel_ingot 64
give @s cc:tin_ingot 64
give @s cc:titanium_ingot 64
give @s cc:tungsten_ingot 64
give @s cc:uranium_ingot 64
give @s cc:zinc_ingot 64
give @s cc:copper_ingot 64
give @s cc:brass_ingot 64