give @p cc:adamantite_ores 64
give @p cc:aluminum_ores 64
give @p cc:amethyst_ores 64
give @p cc:black_steel_ores 64
give @p cc:bronze_ores 64
give @p cc:cobalt_ores 64
give @p cc:electrum_ores 64
give @p cc:lead_ores 64
give @p cc:mythril_ores 64
give @p cc:nickel_ores 64
give @p cc:platinum_ores 64
give @p cc:silver_ores 64
give @p cc:steel_ores 64
give @p cc:tin_ores 64
give @p cc:titanium_ores 64
give @p cc:tungsten_ores 64
give @p cc:uranium_ores 64
give @p cc:zinc_ores 64
give @p cc::copper_ores 64
give @p cc:brass_ores 64