give @s cc:adamantite_ores 64
give @s cc:aluminum_ores 64
give @s cc:amethyst_ores 64
give @s cc:black_steel_ores 64
give @s cc:bronze_ores 64
give @s cc:cobalt_ores 64
give @s cc:electrum_ores 64
give @s cc:lead_ores 64
give @s cc:mythril_ores 64
give @s cc:nickel_ores 64
give @s cc:platinum_ores 64
give @s cc:silver_ores 64
give @s cc:steel_ores 64
give @s cc:tin_ores 64
give @s cc:titanium_ores 64
give @s cc:tungsten_ores 64
give @s cc:uranium_ores 64
give @s cc:zinc_ores 64
give @s cc:copper_ores 64
give @s cc:brass_ores 64