give @s cc:adamantite_ore 64
give @s cc:aluminum_ore 64
give @s cc:amethyst_ore 64
give @s cc:black_steel_ore 64
give @s cc:bronze_ore 64
give @s cc:cobalt_ore 64
give @s cc:electrum_ore 64
give @s cc:lead_ore 64
give @s cc:mythril_ore 64
give @s cc:nickel_ore 64
give @s cc:platinum_ore 64
give @s cc:silver_ore 64
give @s cc:steel_ore 64
give @s cc:tin_ore 64
give @s cc:titanium_ore 64
give @s cc:tungsten_ore 64
give @s cc:uranium_ore 64
give @s cc:zinc_ore 64
give @s cc:copper_ore 64
give @s cc:brass_ore 64